# This a template for .rtx.toml for python
[env]
PYTHON_KEYRING_BACKEND = 'keyring.backends.null.Keyring'
# PYTHONPATH = <some path>

[tools]
python = {version='3.12.0', virtualenv='{{env.HOME}}/.pyenv/versions/3.12.0/envs/odmn-static'}

[settings]
experimental = true
